version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: expo
    versions:
    - 40.0.1
    - 41.0.0
  - dependency-name: react-redux
    versions:
    - 7.2.2
    - 7.2.3
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: expo-constants
    versions:
    - 10.0.1
  - dependency-name: expo-permissions
    versions:
    - 11.0.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: react-navigation
    versions:
    - 4.4.3
  - dependency-name: jest-expo
    versions:
    - 34.0.1
